name: 'Continuous Integration'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Allows us to run the workflow manually from the UI
  workflow_dispatch:

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
      
      - name: Run Prettier
        run: npm run prettier:check
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: http://test.com
      VITE_SUPABASE_KEY: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: npm
      
      - name: Install dependencies
        run: npm ci

      - name: Setup supabase
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: npx supabase db start

      - name: Run tests
        run: npm run test
